export const GET_DIRECTIONS = "GET_DIRECTIONS";
export const SET_DIRECTION_BOOK = "SET_DIRECTION_BOOK";
export const REMOVE_DIRECTION_BOOK = "REMOVE_DIRECTION_BOOK";

export const GET_STATIONS = "GET_STATIONS";
export const SET_STATION_BOOK = "SET_STATION_BOOK";
export const REMOVE_STATION_BOOK = "REMOVE_STATION_BOOK";

export const CHANGE_THEME = "CHANGE_THEME";
export const UPDATE_THEME = "UPDATE_THEME";
